backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  - name: "blog"
    label: "Blog"
    folder: "src/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - name: "contentKey"
        widget: "hidden"
        default: "blog"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
      - label: "Body"
        name: "body"
        widget: "markdown"
      - label: "Post Image"
        name: "postImage"
        widget: "image"
  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pageData/index.md"
        label: "Index Page"
        name: "index-page"
        fields:
          - name: "contentKey"
            widget: "hidden"
            default: "indexPage"
          - label: "Tagline"
            name: "tagline"
            widget: "string"
          - label: "Hero Image"
            name: "heroImage"
            widget: "image"
          - label: "Sub Tagline"
            name: "subTagline"
            widget: "string"
          - label: "Service 1 Title"
            name: "service1Title"
            widget: "string"
          - label: "Service 1 Description"
            name: "service1Description"
            widget: "string"
          - label: "Service 1 Image"
            name: "service1Image"
            widget: "image"
          - label: "Service 2 Title"
            name: "service2Title"
            widget: "string"
          - label: "Service 2 Description"
            name: "service2Description"
            widget: "string"
          - label: "Service 2 Image"
            name: "service2Image"
            widget: "image"
          - label: "Service 3 Title"
            name: "service3Title"
            widget: "string"
          - label: "Service 3 Description"
            name: "service3Description"
            widget: "string"
          - label: "Service 3 Image"
            name: "service3Image"
            widget: "image"
          - label: "Welcome Title"
            name: "welcomeTitle"
            widget: "string"
          - label: "Body"
            name: "body"
            widget: "markdown"

